In [20]:
import pandas as pd

from [jacklich10/nfl_draft_data:](https://github.com/jacklich10/nfl-draft-data)

If you attempt to read in the .csv files in R with the commonly used readr::read_csv function, please use the parameter guess_max = 13000 to avoid parsing errors (this has to do with how readr guesses column types using only the first 1000 rows). Alternatively, use the read.csv function which will handle this without intervention.

from https://github.com/jacklich10/nfl-draft-data: 

If you are joining the datasets together, the value player_id is uniquely identified across all data. 
Be wary of pos_abbr, as the abbreviations sometimes (though rarely) differ across datasets. I have had no issues with school, school_name, and school_abbr, but player_id will always join the data correctly.

If you are joining in ESPN college QBR statistics from college_qbr.csv, join by guid and player_name

## nfl_draft_prospects.csv

ESPN Information on previous NFL draft prospects dating back to 1967 (first year of the common draft). 
If the player has NA values for pick, overall, and round, it means he went undrafted or the draft has not occurred yet (for current year prospects).

In [26]:
# Import CSV for Prospects

# data on when a prospect was drafted, which team drafted them.
csv_prospects = r"Resources\nfl_draft_prospects.csv"
prospects_df = pd.read_csv(csv_prospects)

display('/n draft_prospects:')
display(prospects_df.head())
# display(prospects_df.info())

'/n draft_prospects:'

,draft_year,player_id,player_name,position,pos_abbr,school,school_name,school_abbr,link,pick,...,team,team_abbr,team_logo_espn,guid,weight,height,pos_rk,ovr_rk,grade,player_image
0,1967,23590,Bubba Smith,Defensive End,DE,Michigan State,Spartans,MSU,http://insider.espn.com/nfl/draft/player/_/id/...,1.0,...,Baltimore Colts,IND,https://a.espncdn.com/i/teamlogos/nfl/500/scor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1967,23591,Clinton Jones,Running Back,RB,Michigan State,Spartans,MSU,http://insider.espn.com/nfl/draft/player/_/id/...,2.0,...,Minnesota Vikings,MIN,https://a.espncdn.com/i/teamlogos/nfl/500/scor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1967,23592,Steve Spurrier,Quarterback,QB,Florida,Gators,FLA,http://insider.espn.com/nfl/draft/player/_/id/...,3.0,...,San Francisco 49ers,SF,https://a.espncdn.com/i/teamlogos/nfl/500/scor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1967,23593,Bob Griese,Quarterback,QB,Purdue,Boilermakers,PUR,http://insider.espn.com/nfl/draft/player/_/id/...,4.0,...,Miami Dolphins,MIA,https://a.espncdn.com/i/teamlogos/nfl/500/scor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1967,23594,George Webster,Linebacker,LB,Michigan State,Spartans,MSU,http://insider.espn.com/nfl/draft/player/_/id/...,5.0,...,Houston Oilers,TEN,https://a.espncdn.com/i/teamlogos/nfl/500/scor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
qb_prospects_df = prospects_df.query("position =='Quarterback' or pos_abbr == 'QB'")

display(qb_prospects_df.head())
display(qb_prospects_df.info())
display(qb_prospects_df.columns)

,draft_year,player_id,player_name,position,pos_abbr,school,school_name,school_abbr,link,pick,...,team,team_abbr,team_logo_espn,guid,weight,height,pos_rk,ovr_rk,grade,player_image
2,1967,23592,Steve Spurrier,Quarterback,QB,Florida,Gators,FLA,http://insider.espn.com/nfl/draft/player/_/id/...,3.0,...,San Francisco 49ers,SF,https://a.espncdn.com/i/teamlogos/nfl/500/scor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1967,23593,Bob Griese,Quarterback,QB,Purdue,Boilermakers,PUR,http://insider.espn.com/nfl/draft/player/_/id/...,4.0,...,Miami Dolphins,MIA,https://a.espncdn.com/i/teamlogos/nfl/500/scor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1967,23614,Don Horn,Quarterback,QB,San Diego State,Aztecs,SDSU,http://insider.espn.com/nfl/draft/player/_/id/...,25.0,...,Green Bay Packers,GB,https://a.espncdn.com/i/teamlogos/nfl/500/scor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1967,23616,Bo Burris,Quarterback,QB,Houston,Cougars,HOU,http://insider.espn.com/nfl/draft/player/_/id/...,1.0,...,New Orleans Saints,NO,https://a.espncdn.com/i/teamlogos/nfl/500/scor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1967,23619,Bob Davis,Quarterback,QB,Virginia,Cavaliers,UVA,http://insider.espn.com/nfl/draft/player/_/id/...,4.0,...,Houston Oilers,TEN,https://a.espncdn.com/i/teamlogos/nfl/500/scor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
Index: 619 entries, 2 to 13350
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   draft_year      619 non-null    int64
 1   player_id       619 non-null    int64
 2   player_name     619 non-null    object
 3   position        619 non-null    object
 4   pos_abbr        619 non-null    object
 5   school          609 non-null    object
 6   school_name     609 non-null    object
 7   school_abbr     606 non-null    object
 8   link            619 non-null    object
 9   pick            555 non-null    float64
 10  overall         555 non-null    float64
 11  round           555 non-null    float64
 12  traded          555 non-null    object
 13  trade_note      222 non-null    object
 14  team            555 non-null    object
 15  team_abbr       555 non-null    object
 16  team_logo_espn  554 non-null    object
 17  guid            299 non-null    object
 18  weight          281 non-null    float64
 19  height          280 non-null    float64
 20  pos_rk          278 non-null    float64
 21  ovr_rk          248 non-null    float64
 22  grade           278 non-null    float64
 23  player_image    70 non-null     object
dtypes: float64(8), int64(2), object(14)
memory usage: 120.9+ KB

None

Index(['draft_year', 'player_id', 'player_name', 'position', 'pos_abbr',
       'school', 'school_name', 'school_abbr', 'link', 'pick', 'overall',
       'round', 'traded', 'trade_note', 'team', 'team_abbr', 'team_logo_espn',
       'guid', 'weight', 'height', 'pos_rk', 'ovr_rk', 'grade',
       'player_image'],
      dtype='object')

In [28]:
# Count NaN, 0 values in each column
nan_counts = qb_prospects_df.isna().sum()
zero_counts = (qb_prospects_df == 0).sum()

print("NaN values:\n", nan_counts)
print("\n0 values:\n", zero_counts)

NaN values:
 draft_year          0
player_id           0
player_name         0
position            0
pos_abbr            0
school             10
school_name        10
school_abbr        13
link                0
pick               64
overall            64
round              64
traded             64
trade_note        397
team               64
team_abbr          64
team_logo_espn     65
guid              320
weight            338
height            339
pos_rk            341
ovr_rk            371
grade             341
player_image      549
dtype: int64

0 values:
 draft_year          0
player_id           0
player_name         0
position            0
pos_abbr            0
school              0
school_name         0
school_abbr         0
link                0
pick                0
overall             0
round               0
traded            497
trade_note          0
team                0
team_abbr           0
team_logo_espn      0
guid                0
weight              0
height              0
pos_rk              0
ovr_rk              0
grade               0
player_image        0
dtype: int64

In [29]:
# Drop unnecessary/redundant columns
drop = ['position', 'school_name', 'school_abbr', 'link', 'team_logo_espn','player_image']

prospects_df = qb_prospects_df.drop(columns=drop)
display('prospects_df')
display(prospects_df.head())
display(prospects_df.info())

'prospects_df'

,draft_year,player_id,player_name,pos_abbr,school,pick,overall,round,traded,trade_note,team,team_abbr,guid,weight,height,pos_rk,ovr_rk,grade
2,1967,23592,Steve Spurrier,QB,Florida,3.0,3.0,1.0,False,from Atlanta,San Francisco 49ers,SF,NaN,NaN,NaN,NaN,NaN,NaN
3,1967,23593,Bob Griese,QB,Purdue,4.0,4.0,1.0,False,NaN,Miami Dolphins,MIA,NaN,NaN,NaN,NaN,NaN,NaN
24,1967,23614,Don Horn,QB,San Diego State,25.0,25.0,1.0,False,NaN,Green Bay Packers,GB,NaN,NaN,NaN,NaN,NaN,NaN
26,1967,23616,Bo Burris,QB,Houston,1.0,27.0,2.0,False,NaN,New Orleans Saints,NO,NaN,NaN,NaN,NaN,NaN,NaN
29,1967,23619,Bob Davis,QB,Virginia,4.0,30.0,2.0,False,NaN,Houston Oilers,TEN,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
Index: 619 entries, 2 to 13350
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   draft_year   619 non-null    int64
 1   player_id    619 non-null    int64
 2   player_name  619 non-null    object
 3   pos_abbr     619 non-null    object
 4   school       609 non-null    object
 5   pick         555 non-null    float64
 6   overall      555 non-null    float64
 7   round        555 non-null    float64
 8   traded       555 non-null    object
 9   trade_note   222 non-null    object
 10  team         555 non-null    object
 11  team_abbr    555 non-null    object
 12  guid         299 non-null    object
 13  weight       281 non-null    float64
 14  height       280 non-null    float64
 15  pos_rk       278 non-null    float64
 16  ovr_rk       248 non-null    float64
 17  grade        278 non-null    float64
dtypes: float64(8), int64(2), object(8)
memory usage: 91.9+ KB

None

In [ ]:
# merged_df = merged_df.reindex(sorted(merged_df.columns), axis=1)
# display(merged_df[merged_df['draft_year'] > 2004].head(60))
# display(merged_df.info())
# merged_df.columns

In [30]:
#Export csv for Prospects
csv_path = r"Resources\nfl_draft_prospects_clean.csv"
prospects_df.to_csv(csv_path, index=False)

In [31]:
# merge (prospects_df - player_name, profiles_df - player_name_prof) using fuzzy wuzzy, to allow for some possible differences in the way the name is spelled. 
# print an indicator when there is NOT a match

# Method:
# 1. Create new column 'player_name_match' in dataframe 1 prospects_df
# For each value of player_name, search 'player_name_prof' in dataframe 2: profiles_df using process.extractOne to get the best match (or None if no good match).
#  this best match gets added to 'player_name_match' in dataframe 1 prospects_df
# 2. Then, merge dataframe 1 prospects_df (on 'player_name_match') and dataframe 2 profiles_df (on 'player_name_prof')
#   Maintain the original 'player_name' in dataframe 1 for reference.

# pip install fuzzywuzzy
# Uses slow pure-python SequenceMatcher;  Install python-Levenshtein an optional dependency that speeds things 
# pip install python-Levenshtein

from fuzzywuzzy import process

# Find the best match for each player name in qb_profiles_clean_df
def get_best_match(name, choices, threshold=80):
#  process.extractOne returns tuple w/ 3 elements: match, score, and the index.
    match, score, _ = process.extractOne(name, choices) 
    return match if score > threshold else None

# Create the 'player_name_match' column
prospects_df['player_name_match'] = prospects_df['player_name'].apply(
    lambda x: get_best_match(x, profiles_df['player_name_prof'])
)

# Merge the dataframes
merged_df = pd.merge(
    prospects_df,
    profiles_df,
    left_on='player_name_match',
    right_on='player_name_prof',
    how='outer',
    indicator=True
)

display(merged_df.head())
display(merged_df.tail())

,draft_year,player_id,player_name,pos_abbr,school,pick,overall,round,traded,trade_note,...,weight_prof,height_prof,school_prof,pos_rk_prof,ovr_rk_prof,grade_prof,text1_prof,text2_prof,text3_prof,_merge
0,1967,23592,Steve Spurrier,QB,Florida,3.0,3.0,1.0,False,from Atlanta,...,NaN,NaN,Florida,NaN,NaN,NaN,NaN,NaN,NaN,both
1,1967,23593,Bob Griese,QB,Purdue,4.0,4.0,1.0,False,NaN,...,NaN,NaN,Purdue,NaN,NaN,NaN,NaN,NaN,NaN,both
2,1967,23614,Don Horn,QB,San Diego State,25.0,25.0,1.0,False,NaN,...,NaN,NaN,San Diego State,NaN,NaN,NaN,NaN,NaN,NaN,both
3,1967,23616,Bo Burris,QB,Houston,1.0,27.0,2.0,False,NaN,...,NaN,NaN,Houston,NaN,NaN,NaN,NaN,NaN,NaN,both
4,1967,23619,Bob Davis,QB,Virginia,4.0,30.0,2.0,False,NaN,...,NaN,NaN,Virginia,NaN,NaN,NaN,NaN,NaN,NaN,both

,draft_year,player_id,player_name,pos_abbr,school,pick,overall,round,traded,trade_note,...,weight_prof,height_prof,school_prof,pos_rk_prof,ovr_rk_prof,grade_prof,text1_prof,text2_prof,text3_prof,_merge
616,2021,104814,Jamie Newman,QB,Georgia,NaN,NaN,NaN,NaN,NaN,...,234.0,74.875,Georgia,9.0,184.0,55.0,"Newman has average height, a sturdy build and ...",Newman is a developmental prospect with a good...,NaN,both
617,2021,105211,Feleipe Franks,QB,Arkansas,NaN,NaN,NaN,NaN,NaN,...,234.0,78.625,Arkansas,11.0,239.0,39.0,Franks has a big-time arm. He lacks ideal rele...,Franks is a developmental quarterback prospect...,NaN,both
618,2021,105151,Shane Buechele,QB,SMU,NaN,NaN,NaN,NaN,NaN,...,210.0,72.250,SMU,13.0,260.0,36.0,Buechele is a shorter quarterback who thrives ...,Buechele is a shorter quarterback who is very ...,NaN,both
619,2021,105349,Zach Smith,QB,Tulsa,NaN,NaN,NaN,NaN,NaN,...,222.0,75.375,Tulsa,14.0,311.0,31.0,NaN,NaN,NaN,both
620,2021,105467,K.J. Costello,QB,Mississippi State,NaN,NaN,NaN,NaN,NaN,...,227.0,76.625,Mississippi State,15.0,345.0,30.0,NaN,NaN,NaN,both