In [9]:
import pandas as pd

# want to merge Career statistics, earnings data
#   for use in analyzing a quarterback's success in the NFL and what metrics seem to be the most
#   important to determine success.

#Import CSVs
csv_path = "../Resources/qb_career_stats.csv"
stats_df = pd.read_csv(csv_path)

csv_path = "../Resources/qb_earnings.csv"
earnings_df = pd.read_csv(csv_path)

In [11]:
display(stats_df.head())
display(stats_df.info())

,Player,pass_yds,years_active,team,comp,att,pass_td,passer_rate,int,sacks,lost_yards,pick_6,pass_yards_game,comp_%,int_%,comebacks,game_win_drive
0,Tom Brady,89214.0,2000-2022,2TM,7753.0,12050.0,649.0,97.2,212.0,565.0,3576.0,18.0,266.3,64.3%,1.8%,46.0,58.0
1,Drew Brees,80358.0,2001-2020,2TM,7142.0,10551.0,571.0,98.7,243.0,420.0,2991.0,27.0,280.0,67.7%,2.3%,36.0,53.0
2,Peyton Manning+,71940.0,1998-2015,2TM,6125.0,9380.0,539.0,96.5,251.0,303.0,1953.0,27.0,270.5,65.3%,2.7%,43.0,54.0
3,Brett Favre+,71838.0,1991-2010,4TM,6300.0,10169.0,508.0,86.0,336.0,525.0,3487.0,32.0,237.9,62.0%,3.3%,28.0,43.0
4,Ben Roethlisberger,64088.0,2004-2021,pit,5440.0,8443.0,418.0,93.5,211.0,554.0,3677.0,18.0,257.4,64.4%,2.5%,41.0,53.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 481 entries, 0 to 480
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Player           481 non-null    object
 1   pass_yds         250 non-null    float64
 2   years_active     481 non-null    object
 3   team             481 non-null    object
 4   comp             250 non-null    float64
 5   att              251 non-null    float64
 6   pass_td          251 non-null    float64
 7   passer_rate      214 non-null    float64
 8   int              251 non-null    float64
 9   sacks            250 non-null    float64
 10  lost_yards       250 non-null    float64
 11  pick_6           258 non-null    float64
 12  pass_yards_game  214 non-null    float64
 13  comp_%           214 non-null    object
 14  int_%            214 non-null    object
 15  comebacks        261 non-null    float64
 16  game_win_drive   266 non-null    float64
dtypes: float64(12), object(5)
memory usage: 64.0+ KB

None

In [12]:
display(earnings_df.head())
display(earnings_df.info())

,Player,Year_Drafted,Year_Final,Career Earnings (millions),Cap-Inflated Earnings (millions),Earnings By Team Dict
0,Aaron Rodgers,2005,9999,343.531,546.133,"{'Packers': 306.642, 'Jets': 36.889}"
1,Matt Stafford,2009,9999,328.000,507.909,"{'Lions': 219.0, 'Rams': 109.0}"
2,Tom Brady,2000,2022,317.620,600.483,"{'Patriots': 230.324, 'Buccaneers': 87.296}"
3,Matt Ryan,2008,2022,306.206,501.678,"{'Falcons': 269.5, 'Colts': 36.706}"
4,Russell Wilson,2012,9999,305.340,408.432,"{'Seahawks': 181.34, 'Broncos': 124.0}"

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Player                            391 non-null    object
 1   Year_Drafted                      391 non-null    int64
 2   Year_Final                        391 non-null    int64
 3   Career Earnings (millions)        391 non-null    float64
 4   Cap-Inflated Earnings (millions)  391 non-null    float64
 5   Earnings By Team Dict             391 non-null    object
dtypes: float64(2), int64(2), object(2)
memory usage: 18.5+ KB

None

In [13]:
display(hof_df.head())
display(hof_df.info())

,Player,Pos,hof_induct,yr_first,yr_last,all_pros,pro_bowls,pri_start_yrs,wAV,games_played,...,rush_yds,rush_tds,rush_long,pass_int,sacked,rush_yds.1,rush_att.1,rush_yds.2,rush_tds.1,rush_long.1
0,Peyton Manning,QB,2021,1998,2015,7,14,17,176,266,...,71940,539,86,251,303.0,1953,431,667,18,33
1,Kurt Warner,QB,2017,1998,2009,2,4,8,96,124,...,32344,208,85,128,260.0,1669,173,286,3,23
2,Brett Favre,QB,2016,1991,2010,3,11,19,158,302,...,71838,508,99,336,525.0,3487,602,1844,14,40
3,Ken Stabler,QB,2016,1970,1984,1,4,11,93,184,...,27938,194,88,222,281.0,2514,118,93,4,18
4,Troy Aikman,QB,2006,1989,2000,0,6,12,96,165,...,32942,165,90,141,259.0,1748,327,1016,9,25

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player         29 non-null     object
 1   Pos            29 non-null     object
 2   hof_induct     29 non-null     int64
 3   yr_first       29 non-null     int64
 4   yr_last        29 non-null     int64
 5   all_pros       29 non-null     int64
 6   pro_bowls      29 non-null     int64
 7   pri_start_yrs  29 non-null     int64
 8   wAV            29 non-null     int64
 9   games_played   29 non-null     int64
 10  pass_comps     29 non-null     int64
 11  rush_att       29 non-null     int64
 12  rush_yds       29 non-null     int64
 13  rush_tds       29 non-null     int64
 14  rush_long      29 non-null     int64
 15  pass_int       29 non-null     int64
 16  sacked         26 non-null     float64
 17  rush_yds.1     29 non-null     int64
 18  rush_att.1     29 non-null     int64
 19  rush_yds.2     29 non-null     int64
 20  rush_tds.1     29 non-null     int64
 21  rush_long.1    29 non-null     int64
dtypes: float64(1), int64(19), object(2)
memory usage: 5.1+ KB

None

In [ ]:
#Export csv
csv_path = "../Resources/.csv"
df_ .to_csv(csv_path, index=False)